### ISSUE TITLE
Center Aligned View Width

### ISSUE THREAD

**Issue by calebd** [oarrabi/OAStackView#40] opened 2015-08-20 16:58 UTC
Center aligned views are allowed to be wider than the stack view. It would be great if stack view added a width constraint to views such that they may not be wider than the stack view itself.

Also it would be cool if we can get another tagged, stable release!

**Comment by mthole-old** [comment] 2015-08-23 00:51
@calebd Can you confirm that UIStackView on iOS 9 has the behavior your describe/desire?

**Comment by calebd** [comment] 2015-08-24 20:00
#42

**Comment by calebd** [comment] 2015-08-24 20:04
`UIStackView` does not let center aligned views go wider than the stack view itself. Why would it allow that?

A quick test: Put a multi line label with a lot of text in a width-constrained, center-aligned stack view. Notice that the stack view height grows while restricting the label to its width.

**Comment by delebedev** [comment] 2015-09-24 09:00
@calebd can you please check 0.2.0 tag, it works the same way as OAStackView for me (tried to reproduce your setup:

```
    OAStackView *stackView = [OAStackView new];
    stackView.translatesAutoresizingMaskIntoConstraints = NO;
    [self.view addSubview:stackView];

    UILayoutGuide *margin = self.view.layoutMarginsGuide;
    [stackView.topAnchor constraintEqualToAnchor:margin.topAnchor constant:16.0].active = YES;
    [stackView.leadingAnchor constraintEqualToAnchor:margin.leadingAnchor constant:50].active = YES;
    //[stackView.bottomAnchor constraintEqualToAnchor:margin.bottomAnchor constant:-16.0].active = YES;
    [stackView.trailingAnchor constraintEqualToAnchor:margin.trailingAnchor constant:-50].active = YES;

    stackView.axis = UILayoutConstraintAxisVertical;
    stackView.distribution = UIStackViewDistributionFill;
    stackView.alignment = UIStackViewAlignmentCenter;
    stackView.spacing = 0.0;

    UIView *redView = [UIView new];
    redView.translatesAutoresizingMaskIntoConstraints = NO;
    redView.backgroundColor = [UIColor redColor];
    [redView.heightAnchor constraintEqualToConstant:100].active = YES;
    [redView.widthAnchor constraintEqualToConstant:50].active = YES;

    UILabel *text = [[UILabel alloc] init];
    text.text = @"ofofo ofofo ofofoof ofof ofofo fofo ofofo ofofofo ofofof ofofofo ofofofo ofofofo ofo foofo fo";
    text.numberOfLines = 0;

    [stackView addArrangedSubview:text];
    [stackView addArrangedSubview:redView];
```

**Comment by nsomar** [comment] 2015-11-24 23:00
@calebd  I am closing this issue since there have been no feedback from your side.
Please feel free to reopen it if the issue persists.

**Closed as completed by nsomar** 2015-11-24 23:00 UTC
Labels: bug, help wanted
